feat: :sparkles: Create BackToTop component
codegouvfr/react-dsfr pull request #139
Opened 2023-06-09 06:50 UTC by sylvainlg

2023-06-09 23:03 UTC, garronej requested changes
Thanks a lot for your work, here is my review.

2023-06-12 14:09 UTC, garronej requested changes
Thank you for your work, here is my review

2023-07-08 18:22 UTC, garronej commented on src/BackToTop.tsx
> +    anchor?: string;
@sylvainlg up

2023-07-08 18:23 UTC, garronej requested changes
Hello @sylvainlg,  

This has to be adressed: https://github.com/codegouvfr/react-dsfr/pull/139#discussion_r1226726757

2026-08-29 10:14 UTC, kevbarns commented
@sylvainlg Cette PR est ouverte depuis juin 2023 avec trois revues « changes requested » de @garronej, dont la dernière du 08/07/2023 pointait un seul point restant : https://github.com/codegouvfr/react-dsfr/pull/139#discussion_r1226726757

Ce point n'a jamais été traité. Pour mémoire, il demandait que sans ancre explicite, le comportement par défaut soit un scroll fluide vers le haut de page — ce qui impose un `<button>` stylé `fr-link` plutôt qu'un `<a>` sans `href` valide, et une `ref` plutôt qu'un sélecteur CSS, conformément au reste de la lib. Restaient aussi deux suggestions mécaniques : `export default BackToTop` et une story pour la variante alignée à droite.

@sylvainlg comptez-vous reprendre cette PR ? Si oui, elle a besoin d'un rebase sur `main` avant tout : trois ans se sont écoulés et le code environnant a changé.

Si vous n'avez plus la disponibilité, dites-le simplement — le composant reste utile et quelqu'un peut repartir de votre travail. @garronej dans ce cas, faut-il fermer cette PR et ouvrir une issue « Create BackToTop component » qui reprenne vos retours de 2023 ?

2026-08-31 07:13 UTC, sylvainlg commented
Bonjour

Oui désolé, j'ai changé de projet depuis, vous pouvez bien entendu reprendre ce qui est exploitable pour rendre disponible le composant avec les dernières évolutions de la lib.

2026-08-31 09:18 UTC, kevbarns commented
Merci @sylvainlg, et merci d'avoir pris le temps de répondre après tout ce temps.

J'ai repris votre travail dans #516 : la structure, le nommage des props et vos deux stories y sont conservés. La seule remarque restée ouverte ici, https://github.com/codegouvfr/react-dsfr/pull/139#discussion_r1226726757, est traitée par une prop `targetRef` qui rend un `<button type="button">` stylé `fr-link`, scrolle la cible et y déplace le focus.

Le défaut reste l'ancre `#top` de votre implémentation d'origine, et c'est délibéré : la doc DSFR précise que l'ancre est ce qui replace aussi le focus de navigation en haut de page, ce qu'un scroll scripté ne fait pas. Votre choix initial était donc le bon, l'ajout ne fait que couvrir les pages qui ne peuvent pas poser `id="top"` sur leur élément racine.

Je ferme cette PR au profit de #516. N'hésitez pas à y jeter un œil si le sujet vous intéresse encore.

2026-08-31 09:19 UTC, closed without merging