Feature / updated Select component
codegouvfr/react-dsfr pull request #64
Opened 2023-02-16 11:07 UTC by enguerranws

While checking [this issue](https://github.com/codegouvfr/react-dsfr/issues/62) I noticed that the Select component could be more convenient to use. Based on what [we did on Immersion Facilitée](https://github.com/betagouv/immersion-facile/blob/dev/libs/react-design-system/src/immersionFacile/components/select/Select.tsx) and works a lot like component like `react-select`.

Basically, instead of using `<option>` as children, options are passed as as props (SelectOption<CustomValue>[]), and it can take a `placeholder` prop.

2023-02-17 00:29 UTC, garronej requested changes
Hi @enguerranws,  
Thanks for the PR.  
I have doubt on this though.  
I see your point and this was what I tried to do in the first place then I realise that I didn't know where to put the cursor between ease of use and flexibility.  
Beside we want to be compatible with libraries like [react-hooks-form](https://react-hook-form.com/advanced-usage#SmartFormComponent) .  

I though it was a good strategy to say: "ok, the DSFR is just cosmetic surar on top of native select, le's just define and type what's related to that sugar and avoid constraining anything beyond that."  

Now I admit that the children of `Select` expects `<option />` as children and as it is, it's not enforced by the type system which isn't great so it could be a good idea to accept an array of option props instead of a children, which would improve type safety but not so much ease of use.  

Anyway I updated the documentation, it was bad, I was using the `selected` in a controlled setup...

2023-02-17 00:29 UTC, garronej commented on src/Select.tsx
> +    // selected should not be handled directly by option, but as Select's value
If the component is controlled yes but we want to enable it to be uncontrolled as well.

2023-02-17 00:29 UTC, garronej commented on src/Select.tsx
> +    value: T | number | readonly string[] | undefined;
The type here isn't great, `T` can be anything it gives the impression that our select chan handle arbitrary types...  
It's not the case, to my knoelage only string and number works...

2023-02-17 00:29 UTC, garronej commented on src/Select.tsx
> +    options: SelectOption[];
Maybe an array of option props...

2023-02-18 08:59 UTC, enguerranws commented
Hi @garronej !

> I have doubt on this though.
> I see your point and this was what I tried to do in the first place then I realise that I didn't know where to put the cursor between ease of use and flexibility.
> Beside we want to be compatible with libraries like [react-hooks-form](https://react-hook-form.com/advanced-usage#SmartFormComponent) .
> 
> I though it was a good strategy to say: "ok, the DSFR is just cosmetic surar on top of native select, le's just define and type what's related to that sugar and avoid constraining anything beyond that."
> 
> Now I admit that the children of Select expects <option /> as children and as it is, it's not enforced by the type system which isn't great so it could be a good idea to accept an array of option props instead of a children, which would improve type safety but not so much ease of use.

I see. The purpose of this PR is for the Select component to be used more like the `MainNavigation` or `ButtonsGroup` component (or `react-select`). I see the `options` prop just as another syntaxic declaration of the `<option>` elements, which would be convenient (right now, we have to map our options to render `<option>` element everywhere we use Select element) or, at least, more consistent with other components on the lib.

I'm not sure the controlled/uncontrolled problematic applies here, as long as we consider the `options` prop just to render `<option>` elements. I think we can still work on defaultValue / value on `nativeSelectProps` to handle controlled and uncontrolled behavior (but I'll have to add a selected prop on SelectOption).

Actually, [we are using our Select component this way in `react-hook-form`](https://github.com/betagouv/immersion-facile/blob/dev/front/src/app/components/agency/EditAgency.tsx#L107) and it works "fine" using `register` (but right now, our Select has its caveats - like, we're not forwarding the ref, but I'd rather spend time on `react-dsfr` than on our version, that we will drop in a near future).

Let me know, I still can fix the type issue to be more generic and remove a console.log I forgot.

2023-03-02 09:52 UTC, enguerranws commented
Just reviewed my PR so the Select component:
- infers the type of the options
- only allow value and defaultValue that relies on options' values
- fixed the stories

I had to rewrap the forwardRef and memo in order to make the type explicit, it may not be the most elegant, feel free to rewrite it.

2023-03-02 10:02 UTC, merged

2023-03-07 12:28 UTC, garronej commented
Sorry I had to rollback.  
The component wasn't working properly. I figured out when updating the color picker tool and got a bunch of errors...

2023-03-07 13:20 UTC, enguerranws commented
@garronej feel free to tell me which error you encountered

2023-03-07 15:40 UTC, garronej commented
When I tried to use it as per recommended by the documentation I runtime exceptions.  
I was updating this: https://github.com/codegouvfr/react-dsfr/blob/b25f9bbf7c610cc0e899a7cd2e3db271f678ce7d/stories/ColorHelper/Search.tsx#L145  
I alos got a DM from a freelance saying that the select wasn't working :/  
Also I noticed this that I should have reviewed: https://github.com/codegouvfr/react-dsfr/blob/52220194e6b71334da567a1ac6d8400938d9bc8e/src/Select.tsx#LL64  
It's a conditional hook call.  
And here we treat `placeholder` as boolean which I would like to avoid (using `placeholder !== undefined` instead):  
https://github.com/codegouvfr/react-dsfr/blob/52220194e6b71334da567a1ac6d8400938d9bc8e/src/Select.tsx#LL67C35-L67C35